
FROM python:3.11-slim-bullseye as base
ENV PATH="$PATH:/root/.local/bin"


RUN apt update
RUN apt install --yes libpq-dev python3-dev gcc libc6
RUN pip install poetry==1.5.1

WORKDIR /app
RUN poetry config virtualenvs.create false

ADD pyproject.toml poetry.lock ./
RUN poetry install --no-directory --no-root
RUN rm -f pyproject.toml poetry.lock
ADD src src/

CMD [ "python","-m", "src"]
