services: 
    db:
        image: postgres
        restart: always
        user: postgres
        healthcheck:
          test: ["CMD-SHELL","pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
          interval: 2s
          retries: 10
          start_period: 2s
        volumes:
          - pgdata:/var/lib/postgresql/data
        env_file: .env
    app:
      depends_on:
        - db
      build:
        context: .
      env_file: .env
      ports:
        - 8501:8501

volumes:
  pgdata:
